name: socialtokenizator

services:
  socialtokenizator:
    image: ghcr.io/ivancarlosti/.socialtokenizator:latest
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:80"
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
